### ISSUE TITLE
MP3 Audio download has wrong file extension [Firefox]

### ISSUE THREAD

**Issue by MimzyFang** [ProjectVinyl/ProjectVinyl#20]
## Current Behavior
When trying to download a MP3, it will download a MP3 with a MP4 file extension

## Expected Behavior
it should download a mp3 with the correct file extension

## How to reproduce
1. open Firefox
2. go to, for example [Entropy (AwkwardMarina) -A song about Discord](https://projectvinyl.net/3403)
3. click on the download button 
4. choose mp3 Audio to start download

## System info
used browser: Firefox 98.0.1 (64-bit)
OS: Linux 5.15.28-1-MANJARO

## Affected browsers
only Firefox
Chrome and epiphany(WebKit) are not affected

**Comment by MimzyFang** [comment]
The same issue also applies to WebM

**Comment by Sollace** [comment]
Sorry about that! Issue should be fixed if you check now.
